version: '3.1'
services:
    mongo:
        image: mongo
        restart: always

    redis: 
        image: redis
        restart: always

    easy-mock:
        container_name: easy-mock
        build: ./easy-mock
        restart: always
        ports:
            - 7300:7300
        depends_on:
            - mongo
            - redis
            